### ISSUE TITLE
Render HTML in shwMessage

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/TextbookProject#1]
The datastore saves html nicely.  This is good news.

Now we need to be able to render the html on the showMessage template.  Not quite sure how. I am testing in Task 2.

**Comment by FelixVicis** [comment]
*_Solved. *_
Template injection was reading the string as just that--a string. By changing it's type to template.HTML it now knows to leave the tags alone allowing the browser to represent the HTML in its true form.
