### ISSUE TITLE
Description Field

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/TextbookProject#10]
We should add a description field (long string) to the following models:
1. Catalog
2. Book
3. Chapter
4. Section

Typically there is a paragraph or two for each (check the printed book).  And a way to enter it.

**Comment by FelixVicis** [comment]
Adding to today's docket. Shouldn't be too difficult to add the field in.

**Comment by FelixVicis** [comment]
## Update
- The field Description has been added to the structures: Catalog, Book, Chapter, Section
- The api for the above structures for creation has been updated to accept an optional "Description" field.

Question, how is this description meant to be read on the user side? Should this be wrapped in something? Served directly as html?

**Comment by johnRedden** [comment]
Not sure... I can imagine it will be html with laTex sometimes. So not in json.

I think we need to build that book TOC page to know how and what we need.

**Comment by FelixVicis** [comment]
We have a basic book TOC page at /toc.html?ID=<Book ID>

**Comment by johnRedden** [comment]
I think we need better fake data to see it in action.  However, this looks like a really good start.

http://www.ens-textbooksystem.appspot.com/toc.html?ID=5644406560391168

**Comment by FelixVicis** [comment]
What if we have an api call for description?

Or, another idea, we could have xml datasheets for Catalog, book, chapter, and section. Like we have html returns for objective.

**Comment by johnRedden** [comment]
Yeah... whatever. I am sure usage will dictate changes.  maybe /SectionID=8888&description    Something like that to prompt the html to appear.

**Comment by FelixVicis** [comment]
ok. on it.

**Comment by FelixVicis** [comment]
There are now singular api calls to Catalog, Book, Chapter, and Section found with /api/<type>.xml

All we need now to see these descriptions are pages to post edits to these types. #9 is now considered important to implement.
