### ISSUE TITLE
Exercises per Objective

### ISSUE THREAD

**Issue by FelixVicis** [johnRedden/TextbookProject#17]
We're finally to this point.
# Exercises

At the end of an objective, there should be a list of problems to work on. We will need to decide such things as how detailed we should get with each one, ect.

For now, we're going to hit minimum viable product. We need an html doc tied and retrievable per objective. Really, all we're doing is adding one more layer to structure at this point.

**Comment by johnRedden** [comment]
Yeah we need to sit down and break down and generalize what an exercise
is...

Exercise:
  Instruction: HTML
  Question: HTML
  Answer: HTML
  Objective:  Reference to corresponding objective.

We will need to standardize the list of possible instructions.

**Comment by FelixVicis** [comment]
> Update

```
New Module: Problems
Datastore Table: Exercises
```

``` go
type Exercise struct {
    ID          int64         `datastore:"-"` // Self.ID
    Parent      int64         ``              // Objective ID
    Instruction string        ``              // Instruction Kind. Will need list of exercise kinds.
    Question    template.HTML `datastore:"-"` // Question information, html.
    Solution    template.HTML `datastore:"-"` // Solution to above quesion.
}
```
- Exercises will know their parent but be searchable on their instruction type. 
- May have variable instruction kinds. Possible solution is a local variable of types.
  - This could be a good idea anyways. Keeps front-end models from getting outdated.
- Only loosely tied to an objective.
- Can query images for items tied to it.
- Use Objective Editor as an example of an Exercise Editor

**Comment by FelixVicis** [comment]
## Update
- [x] Created Exercise Model
- [x] Exercise Datastore: Get, Set, Delete
- [x] API: Get, Set, Delete
- [ ] HTML Read, Write

**Comment by FelixVicis** [comment]
## Completed
- [x] Created Exercise Model
- [x] Exercise Datastore: Get, Set, Delete
- [x]  API: Get, Set, Delete
- [x]  HTML Read, Write

We now have Structures, Storage, API's, readers, and editors for exercises. Happy to close this issue.

All api's follow the same format and are documented in file. Wiki documentation will be coming soon.

```
/api/exercises.json  -- Collection exercise reader api
/api/exercise.xml -- singular exercise reader api
/api/makeExercise -- singular exercise writer api
/api/deleteExercise -- singular exercise deleter api
```

The reader is a very cut down version. It'll need to look better, of course, but for now it works. 
The editor follows the same format as the others, it too will need to look better in the future.

```
/read/exercise/:ID -- singular exercise reader html
/edit/Exercise/:ID -- singular exercise writer html
```
