### ISSUE TITLE
Consistent URL system

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/TextbookProject#28]
Would like

**/edit/Objective/:ID**  (instead of:  /edit?ID=5116463811657728 )

Also: 

**/Book/TOC/:ID** (instead of:  toc.html/5688424874901504)

maybe:

**/read/Objective/:ID** (to match the reads and eliminate preview and read -- seems redundant?)

Then to fix all corresponding links in the web app... ugh.

**Comment by FelixVicis** [comment]
Can do. Will record all changed URLs here.

Just as a note, it might be better if TOC is just /TOC/:ID and we move the TOC api under the /api/ directory.

**Comment by johnRedden** [comment]
Ok sounds good. So far I am not using the whole book toc xml api so that should not be a problem.

**Comment by FelixVicis** [comment]
- toc api is now: `/api/toc.xml`

**Will Update as more URLs change**

**Comment by FelixVicis** [comment]
Might as well go in for the whole thing and make the api urls consistant.

How does `/api/create/catalog` and `/api/delete/catalog` sound?

**Comment by FelixVicis** [comment]
_Question_: Does this mean that preview is now outdated?

**Comment by FelixVicis** [comment]
- toc api is now: `/api/toc.xml`
- toc page is now `/toc/:ID`
- objective reader is now `/read/objective/:ID`
- objective editor is now `/edit/objective/:ID`
- all editors are lowercase

**Will Update as more URLs change**

**Comment by johnRedden** [comment]
I am not sure what is different between preview and read?  Just one read for consistency... maybe one clean read... and one branded (eduNetSystems) read?

**Comment by FelixVicis** [comment]
:laughing: Okay. For now, I'll leave preview in as is. Let me know if/when you want this to change. Any thoughts on the api calls?

**Comment by johnRedden** [comment]
The api calls sound great... will have to change alot of links. It's doable and I think worth it.

**Comment by FelixVicis** [comment]
Your the boss, boss. I'll do that now.

**Comment by FelixVicis** [comment]
- toc api is now: `/api/toc.xml`
- toc page is now `/toc/:ID`
- objective reader is now `/read/objective/:ID`
- objective editor is now `/edit/objective/:ID`
- all editors are lowercase
- image creation is now `/api/create/image`
- image deletion is now `/api/delete/image`
- all api readers have stayed the same
- catalog creation is now `/api/create/catalog`
- book creation is now `/api/create/book`
- chapter, section, objective, and exercise creation follows the obvious format.
- all deleters are now `/api/delete/structure` for catalog, book, chapter, section, objective, and exercise

**Will Update as more URLs change**

**Comment by FelixVicis** [comment]
any more of these urls that you wish me to change?

**Comment by johnRedden** [comment]
I have no idea... I'm sure this broke the app.  I will go through it.  Close if you are done.

**Comment by FelixVicis** [comment]
:laughing: Don't worry. It'll be okay. I'll help sort out the urls

**Comment by johnRedden** [comment]
Also, some eyes on the code would be nice.  I think it's clean... except for the datastore $.wait's.  I might work some more tonight... it's kinda fun. And I feel like we are close to an alpha release?

**Comment by FelixVicis** [comment]
Really close.

**Comment by FelixVicis** [comment]
What pages are you working on first. I'd really rather not have push collisions at this stage.

**Comment by johnRedden** [comment]
I'm not working Allen... I have an event to attend.

**Comment by FelixVicis** [comment]
oh! ok free game then. Have fun!
