### ISSUE TITLE
Login On All Pages

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/TextbookProject#29]
Having issues with login on the templated nav.  Do we want login on all pages?  I think we do on the content building side... not needed on the reader side.

If so we need to put work into that.

**Comment by FelixVicis** [comment]
Define work? I already verify login permissions on all pages that require it.

**Comment by johnRedden** [comment]
The **Not john?** and **Logout** not showing on all pages.  Not sure why right now.

http://www.ens-textbooksystem.appspot.com/toc.html/5639274879778816

**Comment by FelixVicis** [comment]
[https://github.com/johnRedden/TextbookProject/blob/master/templates/toc.html#L6](toc.html line 6) Your not passing the information to the header

**Comment by johnRedden** [comment]
Yeah, I had to take the . operator out because I was getting an error somewhere.  I forgot where... left it behind and forgot ... if we get a link to an edit page... I should be able to log in from there?

**Comment by FelixVicis** [comment]
I don't believe our current system allows that behavior. Perhaps the error page could have a login with redirect?

**Comment by johnRedden** [comment]
For this functionality I found: 

`var referrer =  document.referrer;`
then
`window.location = referrer;`

**Comment by FelixVicis** [comment]
:/ Maybe. I'll fiddle with it. I was just going to do it myself on the back end. But this may be better.

**Comment by FelixVicis** [comment]
So, login already has this ability. it's `?redirect`. I actually think that window.location.pathname may be a better direction to go.

**Comment by FelixVicis** [comment]
For all pages that the user is interacting with, User information has been spliced in. Rolled this functionality out for catalogs.html, toc.html, and all editors.
