### ISSUE TITLE
Discuss Exercise Model

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/TextbookProject#31]
Find time to hash out ideas for an exercise model... bring book. Keep it simple.

Instruction: Text
**Question**: HTML/LaTex
**Answer**: HTML/LaTex
**Solution**: HTML/LaTex
Order: int  (devise an ordering system)
Group: Text or ID (could hold instruction and parent - name and description)
Multiple Choice Answers
Ascii-math version of question.
Link to outside notes or resources (maybe in group)

Just ideas, don't freak out!

**Comment by FelixVicis** [comment]
You actually got me at a strange time. I have the online copy you gave me a link to.

### Ideas

So, I'm looking at my copy here and what I see is this:
- An Instruction
  - Group of Questions

If we take each exercise, group them under their instruction; I'd call it a success. 

### Example

> Do This Action
> - Question 1
>   `Answer popup`
> - Question 2
>   `Answer popup`
> - Question 3
>   `Answer popup`
> 
> Do this other Action
> - Question 1
>   `Answer popup`

**Comment by FelixVicis** [comment]
Just put some ideas down, take a look at this:
[Example](http://www.liquid-journal-88820.appspot.com/login?redirect=edit/objective/5742636757417984)

**Comment by johnRedden** [comment]
I can't login as an editor.

What should I be looking for?

Also, pull a recent copy... I added the mathjax typeset.

**Comment by FelixVicis** [comment]
Darn your two emails almost identical with each other. The email your using now is admin.
If that's the case. I'll just delete the other issue then.

**Comment by johnRedden** [comment]
Login not working... delete me as a user and let me log in as a random
stranger.

**Comment by FelixVicis** [comment]
You spell it differently. I had it lowercased. Changed and forced a logout. Try now.

**Comment by johnRedden** [comment]
My google default email is set to: jt.redden@gmail.com  Having different
variants confuses people.

I like the idea of links to the graphing calulator... we will have a solver
soon too.  This is why I wanted an ascii version of the question.  I am not
sure but maybe MathJax can return ascii version so maybe not needed.??
