### ISSUE TITLE
Convert website from HTTP to HTTPS

### ISSUE THREAD

**Issue by FelixVicis** [johnRedden/TextbookProject#38]

**Comment by johnRedden** [comment]
Here is a start: https://cloud.google.com/appengine/docs/go/console/using-custom-domains-and-ssl#before_you_begin

**Comment by FelixVicis** [comment]
More: https://cloud.google.com/appengine/docs/go/console/using-custom-domains-and-ssl#adding_ssl_to_your_custom_domain

**Comment by johnRedden** [comment]
Certificates seem to cost ( Is it worth it?)  : Locate the certificate authority (CA) that you want to use, such as Thawte, Comodo, or other certificate authority, and purchase a certificate.  

Unless we figure out how to self-sign one. Ugh.

**Comment by FelixVicis** [comment]
We cannot self-assign a certificate. The certificates announce from a _verified_ domain that ours is indeed who we say we are. Only the big guys like Google are able to self-sign.

They do cost, and I don't inherently think that we _need_ it. It may be nice in the future but it is ultimately up to you.

**Comment by johnRedden** [comment]
FYI... Canvas uses https and so iFrame content will not load unless https.  Just tested this.  We NEED to set this up.

**Comment by johnRedden** [comment]
Use appspot.com domain when ssl is needed.

https://ens-textbooksystem.appspot.com/

It's cheaper for now...  Done.
