### ISSUE TITLE
Convert login to local procedure

### ISSUE THREAD

**Issue by FelixVicis** [johnRedden/TextbookProject#41]
No more Oauth, we'll handle login internally. Safer that way _surprisingly enough._

**Comment by johnRedden** [comment]
Currently login seems to redirect to index.html.  Try to redirect to referer... maybe this is the trick:

var referrer =  document.referrer;

then

window.location = referrer;

**Comment by FelixVicis** [comment]
Uhh, John, What?
This is specifically about handling user names and passwords internally instead of through OAuth.

**Comment by johnRedden** [comment]
Ok I guess I am confused.  The new login system hopefully can redirect back to the page on which the user clicked the login button.  No big deal.

**Comment by FelixVicis** [comment]
### In Progress

**Comment by FelixVicis** [comment]
### Progress Report

**State is not currently stable on my end, will commit when stable again**
- [x] Change Users to the new storage solution
- [x] Change Permissions to the new storage solution
- [x] Update session to maintain these new structs and not depend on appengine.user
- [x] Change front end to interact with all of this.

**Comment by FelixVicis** [comment]
### Completed

Login is now rolled out. These tables are now invalid: 

> Users
> Logins

Login is now local and stores the information in the most secure way possible on our side. There is a tie in to the old oauth system for specific usages. Will document this new procedure more carefully later.
