### ISSUE TITLE
Clean up of objective editor

### ISSUE THREAD

**Issue by FelixVicis** [johnRedden/TextbookProject#44]
The objective editor is a relic of the first version that we made. The code for all of the other editors is much nicer. It would be awesome if we cleaned up the objective editor so it was much more like the others.

**Comment by johnRedden** [comment]
Which file are you talking about... already fixed the objective editor: here is the link: http://www.ens-textbooksystem.appspot.com/edit/objective/5136307634307072

I think its something like editor_objective.html

**Comment by FelixVicis** [comment]
I meant the contents of editor_objective.html if you look at the JS and HTML it's not quite the same standard as the other editors.

**Comment by johnRedden** [comment]
As best I can do.
