### ISSUE TITLE
[Admin Console] Fix console for new login

### ISSUE THREAD

**Issue by FelixVicis** [johnRedden/TextbookProject#48]
All of these login changes have broken the console usage. Fix as soon as reasonable.

**Comment by johnRedden** [comment]
Try to keep the "sign in with google" functionality if possible.  I just like that.

**Comment by FelixVicis** [comment]
Still there, in login and register.

**Comment by johnRedden** [comment]
email is case sensitive... maybe toLower it ... not sure. Looks nicer now.

http://content.edunetsystems.com/login

I guess register needs to be there too.  Not sure what "remember me" should do?

Gmail not quite working.

**Comment by FelixVicis** [comment]
Document issues with gmail and put it into a new issue. I'll chase that
down later.

Email _should_ be case sensitive. :/ I'll have to remember to verify.

**Comment by johnRedden** [comment]
Login with gmail does not work for me.  Did you test it and it worked for you?
