### ISSUE TITLE
CKeditor MathJax css cut-off in editor only

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/TextbookProject#51]
MathJax renders after css sizing is set and thus looks cut-off in ckEditor.  Very hard to find the problem.

**Comment by FelixVicis** [comment]
After testing and inspecting an example, we've found that nice re-sizing occurs when the mathjax is replaced with an image. We should check the mathjax documentation and see if this is some standard action they can preform or if some other magic is being accomplished here.

**Comment by johnRedden** [comment]
You will have to show me this behavior.  As long as the latex is saved...
the presentation can be made in any way.  I think you can set mathJax to
render svg, images, or MathML... or it's automatic depending on browser.
Now sure though.

**Comment by johnRedden** [comment]
Boy this was hard to fix... wrong config chosen in mathJax cdn link.  This is a LaTex solution, not a MathML solution (MML)

```
OLD: http://cdn.mathjax.org/mathjax/latest/MathJax.js?config=TeX-MML-AM_CHTML
NEW: https://cdn.mathjax.org/mathjax/2.6-latest/MathJax.js?config=TeX-AMS_HTML
```

The solution was to choose the non-MML config setting.  I'm just glad it's fixed!!!
