### ISSUE TITLE
Delete Objective May Lose Exercises

### ISSUE THREAD

**Issue by johnRedden** [johnRedden/TextbookProject#52]
When deleting an objective, do the associated exercises get deleted.  If not, should they?  If they do not, then we should run through and reset parent to some catchall dummy objective so they do not get lost forever.

**Comment by FelixVicis** [comment]
Currently, yes. All media--both text and images--are deleted when it's parent is deleted. I would recommend we keep this behavior for now. This is to keep floating data from taking up space while being generally inaccessible. 

If you do wish for this behavior, we could do something a bit better than a dummy objective by instead making the parent the book ID.
