### ISSUE TITLE
[Bug Report] Large post in editor causes an http:500 error.

### ISSUE THREAD

**Issue by FelixVicis** [johnRedden/TextbookProject#8]
- does not appear on the surface to be the /api call
- appengine seems to have received a really strange call to /edit?message=<ridiculous - length> on a 307(temporary redirect)
- _todo:_ search that call to edit down. it may be a part of the problem.

**Comment by FelixVicis** [comment]
Ah, the joys of bugs..
So, the issue arose from an error in writing the datastore options for the structs.
I wrote ``datastore:,noindex"`` but apparently this is not recognized by the datastore as a well formed option. What I really wanted was ``datastore:",noindex"``

Such silly issues making some really tense moments.

Fixed and closed.

**Comment by johnRedden** [comment]
heh... nice catch.
